In [1]:
import pandas as pd

In [2]:
inputfile = "../data/principal_component.xls"
outfile = "../tmp/pca_ret.xls"

In [5]:
data = pd.read_excel(inputfile, header=None)

In [6]:
data

0     1     2     3     4     5      6     7
0   40.4  24.7   7.2   6.1   8.3   8.7  2.442  20.0
1   25.0  12.7  11.2  11.0  12.9  20.2  3.542   9.1
2   13.2   3.3   3.9   4.3   4.4   5.5  0.578   3.6
3   22.3   6.7   5.6   3.7   6.0   7.4  0.176   7.3
4   34.3  11.8   7.1   7.1   8.0   8.9  1.726  27.5
5   35.6  12.5  16.4  16.7  22.8  29.3  3.017  26.6
6   22.0   7.8   9.9  10.2  12.6  17.6  0.847  10.6
7   48.4  13.4  10.9   9.9  10.9  13.9  1.772  17.8
8   40.6  19.1  19.8  19.0  29.7  39.6  2.449  35.8
9   24.8   8.0   9.8   8.9  11.9  16.2  0.789  13.7
10  12.5   9.7   4.2   4.2   4.6   6.5  0.874   3.9
11   1.8   0.6   0.7   0.7   0.8   1.1  0.056   1.0
12  32.3  13.9   9.4   8.3   9.8  13.3  2.126  17.1
13  38.5   9.1  11.3   9.5  12.2  16.4  1.327  11.6

In [7]:
from sklearn.decomposition import PCA

In [8]:
pca = PCA()

In [9]:
pca.fit(data)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [10]:
pca.components_

array([[ 0.56788461,  0.2280431 ,  0.23281436,  0.22427336,  0.3358618 ,
         0.43679539,  0.03861081,  0.46466998],
       [ 0.64801531,  0.24732373, -0.17085432, -0.2089819 , -0.36050922,
        -0.55908747,  0.00186891,  0.05910423],
       [-0.45139763,  0.23802089, -0.17685792, -0.11843804, -0.05173347,
        -0.20091919, -0.00124421,  0.80699041],
       [-0.19404741,  0.9021939 , -0.00730164, -0.01424541,  0.03106289,
         0.12563004,  0.11152105, -0.3448924 ],
       [-0.06133747, -0.03383817,  0.12652433,  0.64325682, -0.3896425 ,
        -0.10681901,  0.63233277,  0.04720838],
       [ 0.02579655, -0.06678747,  0.12816343, -0.57023937, -0.52642373,
         0.52280144,  0.31167833,  0.0754221 ],
       [-0.03800378,  0.09520111,  0.15593386,  0.34300352, -0.56640021,
         0.18985251, -0.69902952,  0.04505823],
       [-0.10147399,  0.03937889,  0.91023327, -0.18760016,  0.06193777,
        -0.34598258, -0.02090066,  0.02137393]])

In [11]:
pca.components_.shape

(8, 8)

In [12]:
pca.explained_variance_ratio_

array([7.74011263e-01, 1.56949443e-01, 4.27594216e-02, 2.40659228e-02,
       1.50278048e-03, 4.10990447e-04, 2.07718405e-04, 9.24594471e-05])

In [13]:
help(pca)

Help on PCA in module sklearn.decomposition._pca object:

class PCA(sklearn.decomposition._base._BasePCA)
 |  PCA(n_components=None, copy=True, whiten=False, svd_solver='auto', tol=0.0, iterated_power='auto', random_state=None)
 |  
 |  Principal component analysis (PCA).
 |  
 |  Linear dimensionality reduction using Singular Value Decomposition of the
 |  data to project it to a lower dimensional space. The input data is centered
 |  but not scaled for each feature before applying the SVD.
 |  
 |  It uses the LAPACK implementation of the full SVD or a randomized truncated
 |  SVD by the method of Halko et al. 2009, depending on the shape of the input
 |  data and the number of components to extract.
 |  
 |  It can also use the scipy.sparse.linalg ARPACK implementation of the
 |  truncated SVD.
 |  
 |  Notice that this class does not support sparse input. See
 |  :class:`TruncatedSVD` for an alternative with sparse data.
 |  
 |  Read more in the :ref:`User Guide <PCA>`.
 |  
 |  P

In [14]:
data

0     1     2     3     4     5      6     7
0   40.4  24.7   7.2   6.1   8.3   8.7  2.442  20.0
1   25.0  12.7  11.2  11.0  12.9  20.2  3.542   9.1
2   13.2   3.3   3.9   4.3   4.4   5.5  0.578   3.6
3   22.3   6.7   5.6   3.7   6.0   7.4  0.176   7.3
4   34.3  11.8   7.1   7.1   8.0   8.9  1.726  27.5
5   35.6  12.5  16.4  16.7  22.8  29.3  3.017  26.6
6   22.0   7.8   9.9  10.2  12.6  17.6  0.847  10.6
7   48.4  13.4  10.9   9.9  10.9  13.9  1.772  17.8
8   40.6  19.1  19.8  19.0  29.7  39.6  2.449  35.8
9   24.8   8.0   9.8   8.9  11.9  16.2  0.789  13.7
10  12.5   9.7   4.2   4.2   4.6   6.5  0.874   3.9
11   1.8   0.6   0.7   0.7   0.8   1.1  0.056   1.0
12  32.3  13.9   9.4   8.3   9.8  13.3  2.126  17.1
13  38.5   9.1  11.3   9.5  12.2  16.4  1.327  11.6

In [15]:
pca = PCA(3)

In [27]:
pca.fit(data) # 对输入数据 data 进行拟合

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [28]:
low_d = pca.transform(data) # 对原始数据进行降维，返回降维后的数据

In [29]:
low_d

array([[  8.19133694,  16.90402785,   3.90991029],
       [  0.28527403,  -6.48074989,  -4.62870368],
       [-23.70739074,  -2.85245701,  -0.4965231 ],
       [-14.43202637,   2.29917325,  -1.50272151],
       [  5.4304568 ,  10.00704077,   9.52086923],
       [ 24.15955898,  -9.36428589,   0.72657857],
       [ -3.66134607,  -7.60198615,  -2.36439873],
       [ 13.96761214,  13.89123979,  -6.44917778],
       [ 40.88093588, -13.25685287,   4.16539368],
       [ -1.74887665,  -4.23112299,  -0.58980995],
       [-21.94321959,  -2.36645883,   1.33203832],
       [-36.70868069,  -6.00536554,   3.97183515],
       [  3.28750663,   4.86380886,   1.00424688],
       [  5.99885871,   4.19398863,  -8.59953736]])

In [30]:
low_d.shape, type(low_d)

((14, 3), numpy.ndarray)

In [31]:
data.shape, type(data)

((14, 8), pandas.core.frame.DataFrame)

In [32]:
pca.fit?

In [34]:
pd.DataFrame(low_d).to_excel(outfile)

In [35]:
recoved_data = pca.inverse_transform(low_d)

In [37]:
pd.DataFrame(recoved_data)

0          1          2          3          4          5  \
0   41.819450  17.929385   7.427436   6.384238   7.519112   7.955818   
1   26.030335   8.310483  11.092303  10.509411  13.735927  19.292194   
2   12.891203   4.720030   4.155748   3.880840   4.155903   5.953541   
3   21.951070   7.869837   5.612961   5.003632   5.465987   7.326930   
4   33.249462  16.929523   6.970701   6.541840   8.787991   9.478548   
5   35.302237  14.316352  16.196120  15.832114  22.516882  30.256541   
6   22.040430   7.672127   9.964581   9.590427  12.697484  17.740255   
7   47.823443  16.035812  11.119071   9.536231  11.081192  14.244620   
8   40.723333  17.985332  20.145977  19.988463  29.358358  39.045723   
9   24.509818   9.364337   9.520055   9.104715  12.032777  16.334456   
10  13.382574   5.677772   4.160041   3.958361   4.478616   6.085014   
11   1.447831   2.038949   0.877284   1.094674   0.694755   1.139610   
12  32.544004  13.141660   8.856767   8.144768  10.363033  13.129186   
13  37.984811  11.308402  11.300956  10.030286  12.011986  16.617565   

           6          7  
0   1.894502  22.646342  
1   1.556162  10.699913  
2   0.631425   3.100320  
3   1.000434   6.902794  
4   1.768031  25.483793  
5   2.465915  25.944809  
6   1.398867  10.627040  
7   2.124786  16.792651  
8   3.099988  36.259755  
9   1.476801  13.147016  
10  0.698174   5.424433  
11  0.117983   0.478583  
12  1.686274  17.311209  
13  1.801659  10.781342

In [38]:
data

0     1     2     3     4     5      6     7
0   40.4  24.7   7.2   6.1   8.3   8.7  2.442  20.0
1   25.0  12.7  11.2  11.0  12.9  20.2  3.542   9.1
2   13.2   3.3   3.9   4.3   4.4   5.5  0.578   3.6
3   22.3   6.7   5.6   3.7   6.0   7.4  0.176   7.3
4   34.3  11.8   7.1   7.1   8.0   8.9  1.726  27.5
5   35.6  12.5  16.4  16.7  22.8  29.3  3.017  26.6
6   22.0   7.8   9.9  10.2  12.6  17.6  0.847  10.6
7   48.4  13.4  10.9   9.9  10.9  13.9  1.772  17.8
8   40.6  19.1  19.8  19.0  29.7  39.6  2.449  35.8
9   24.8   8.0   9.8   8.9  11.9  16.2  0.789  13.7
10  12.5   9.7   4.2   4.2   4.6   6.5  0.874   3.9
11   1.8   0.6   0.7   0.7   0.8   1.1  0.056   1.0
12  32.3  13.9   9.4   8.3   9.8  13.3  2.126  17.1
13  38.5   9.1  11.3   9.5  12.2  16.4  1.327  11.6

In [39]:
pca.explained_variance_ratio_

array([0.77401126, 0.15694944, 0.04275942])